version: "2.3"

services:
    zookeeper:
        image: zookeeper:3.4
        ports:
            - 2181:2181
        healthcheck:
            test: ["CMD-SHELL", "./bin/zkCli.sh ls /"]
            interval: 10s
            timeout: 10s
            retries: 3

    kafka:
        image: wurstmeister/kafka
        environment:
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
            KAFKA_LISTENERS: "SASL_PLAINTEXT://:9092"
            KAFKA_ADVERTISED_LISTENERS: "SASL_PLAINTEXT://${HOST_IP}:9092"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "SASL_PLAINTEXT:SASL_PLAINTEXT"
            KAFKA_INTER_BROKER_LISTENER_NAME: "SASL_PLAINTEXT"
            KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
            KAFKA_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
            KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN,SCRAM-SHA-256,SCRAM-SHA-512"
            KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/config/kafka-server-jaas.conf"
        volumes:
          - ./files/etc/kafka-server-jaas.conf:/opt/kafka/config/kafka-server-jaas.conf

    demo-kafka-auth:
        image: demokafka
        build:
            context: ./
        environment:
            SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092
            SPRING_CLOUD_STREAM_KAFKA_BINDER_ZKNODES: zookeeper:2181
        depends_on:
            - zookeeper
            - kafka
        ports:
            - 8080:8080

networks:
    default:
        external:
            name: test

