version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:1'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_INTER_BROKER_USER=admin
      - KAFKA_INTER_BROKER_PASSWORD=admin-secret
      - KAFKA_BROKER_USER=kafka
      - KAFKA_BROKER_PASSWORD=kafka-secret

  kafka-client-tool:
      image: kafka-client-tool
      build:
          context: ./
      environment:
          KAFKA_BINDER_BROKERS: kafka:9092
          KAFKA_BINDER_ZKNODES: zookeeper:2181
          TOPIC_NAME: test
          KAFKA_USERNAME: "kafka"
          KAFKA_PASSWORD: "kafka-secret"

      depends_on:
          - zookeeper
          - kafka
      ports:
          - 8080:8080

networks:
    default:
        external:
            name: test
